[project]
name = "print-utils"
version = "0.0.1"
description = "Utility functions for formatted console printing used across the project."
requires-python = ">=3.10"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["print_utils"] 