[project]
name = "print-utils"
version = "0.0.1dev1"
description = "Utilities for formatted console printing."
authors = [
   {name = "VLMHyperBenchTeam", email = "contact@vlmhyperbench.team"},
   {name = "Anton Shiryaev", email = "med.phisiker@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.10"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["print_utils"]

[tool.setuptools.packages.find]
where = ["print_utils"] 